---
pull_request_rules:
  - name: Automatically approve and merge dependabot pull requests
    conditions:
      - author=dependabot[bot]
      - label!=wontfix
    actions:
      review:
        type: APPROVE
        message: Automatically approving dependabot
      merge:
        method: merge
  - name: Automatically merge when the pull request has been approved and there are no comments
    conditions:
      - "#approved-reviews-by>=1"
      - "#changes-requested-reviews-by=0"
    actions:
      merge:
        method: merge
  - name: Ask for reviews on open pull requests
    conditions:
      - -closed
      - -draft
    actions:
      request_reviews:
        teams:
          - Etch
        random_count: 2
  - name: Automatically assign to the pull request author
    conditions:
      - author!=dependabot[bot]
    actions:
      assign:
        users:
          - "{{author}}"
